# Generated by Django 4.0.7 on 2022-09-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_reservation_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='link_img',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
