# Generated by Django 4.0.7 on 2022-09-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_department_link_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='long_description',
            field=models.CharField(default='Bueno bonito barato', max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='short_description',
            field=models.CharField(default='Bueno bonito barato', max_length=100),
        ),
    ]
