# Generated by Django 4.0.7 on 2022-09-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_department_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='long_description',
            field=models.CharField(default='Bueno bonito barato', max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='short_description',
            field=models.CharField(default='3B', max_length=100),
        ),
    ]
