# Generated by Django 4.0.7 on 2022-09-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_department_long_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='commune_id',
            new_name='commune',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='department_type_id',
            new_name='department_type',
        ),
    ]
