# Generated by Django 4.0.7 on 2022-09-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_commune_id_department_commune_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
