# Generated by Django 4.0.7 on 2022-09-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_department_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commune',
            old_name='id_region',
            new_name='region',
        ),
    ]
