# Generated by Django 4.1 on 2022-09-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('commune', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'commune',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mail_address', models.CharField(max_length=100)),
                ('legal_representative', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mail_address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('regular_customer', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('internet', models.BooleanField(blank=True, null=True)),
                ('tv_cable', models.BooleanField(blank=True, null=True)),
                ('heating', models.BooleanField(blank=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=1)),
                ('qty_rooms', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepartmentInventory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('qty', models.BigIntegerField()),
            ],
            options={
                'db_table': 'department_inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepartmentMaintenance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('maintenance_date', models.DateField(blank=True, null=True)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'department_maintenance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepartmentType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'department_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mail_address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employee_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'employee_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('income', models.BigIntegerField()),
                ('egress', models.BigIntegerField()),
                ('total', models.BigIntegerField()),
                ('date_time', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'finance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('guarantee_payment', models.BigIntegerField()),
                ('amount', models.BigIntegerField()),
                ('total_payment', models.BigIntegerField()),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tariff', models.BigIntegerField(blank=True, null=True)),
                ('rental_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty_customer', models.BigIntegerField()),
                ('tour', models.BooleanField(blank=True, null=True)),
                ('reservation_date', models.DateField(blank=True, null=True)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reservation_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hire_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('available', models.BooleanField(blank=True, null=True)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'service_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('hire_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=100)),
                ('id_vehicle', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vehicle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkArea',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'work_area',
                'managed': False,
            },
        ),
    ]
