# Generated by Django 4.1 on 2022-09-06 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('commune', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('internet', models.BooleanField(blank=True, null=True)),
                ('tv_cable', models.BooleanField(blank=True, null=True)),
                ('heating', models.BooleanField(blank=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=1)),
                ('qty_rooms', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='arriendo.commune')),
                ('department_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='arriendo.departmenttype')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='id_region',
            field=models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.DO_NOTHING, to='arriendo.region'),
        ),
    ]
