# Generated by Django 4.1 on 2022-09-03 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arriendo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
